import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

// ── Brand colours ───────────────────────────────
const GREEN    = [27, 107, 58]  as [number,number,number]
const GREEN_LT = [46, 139, 87]  as [number,number,number]
const TEXT     = [17,  24, 39]  as [number,number,number]
const MUTED    = [107,114,128]  as [number,number,number]
const WHITE    = [255,255,255]  as [number,number,number]
const LIGHT    = [247,248,250]  as [number,number,number]

// ── Helper: add branded header ──────────────────
function addHeader(doc: jsPDF, title: string, subtitle?: string) {
  // Green bar
  doc.setFillColor(...GREEN)
  doc.rect(0, 0, 210, 28, 'F')

  // Logo text
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(18)
  doc.setTextColor(...WHITE)
  doc.text('Gigs4You', 14, 14)

  // Tagline
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8)
  doc.text('Field Agent Management Platform', 14, 20)

  // Title on right
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.text(title, 196, 14, { align: 'right' })
  if (subtitle) {
    doc.setFontSize(8)
    doc.setFont('helvetica', 'normal')
    doc.text(subtitle, 196, 20, { align: 'right' })
  }

  // Reset text colour
  doc.setTextColor(...TEXT)
}

// ── Helper: add footer ──────────────────────────
function addFooter(doc: jsPDF, pageCount: number) {
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(...MUTED)
    doc.text(
      `Generated by Gigs4You  ·  ${new Date().toLocaleString('en-KE')}  ·  Page ${i} of ${pageCount}`,
      105, 290, { align: 'center' }
    )
    doc.setDrawColor(...LIGHT)
    doc.line(14, 286, 196, 286)
  }
}

// ── Helper: section title ───────────────────────
function sectionTitle(doc: jsPDF, text: string, y: number) {
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(10)
  doc.setTextColor(...GREEN)
  doc.text(text.toUpperCase(), 14, y)
  doc.setDrawColor(...GREEN_LT)
  doc.line(14, y + 1.5, 196, y + 1.5)
  doc.setTextColor(...TEXT)
  doc.setFont('helvetica', 'normal')
  return y + 7
}

// ── Helper: KPI row ─────────────────────────────
function kpiRow(doc: jsPDF, items: {label:string; value:string|number}[], y: number) {
  const colW = 182 / items.length
  items.forEach((item, i) => {
    const x = 14 + i * colW
    doc.setFillColor(...LIGHT)
    doc.roundedRect(x, y, colW - 3, 14, 2, 2, 'F')
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(13)
    doc.setTextColor(...GREEN)
    doc.text(String(item.value), x + (colW - 3) / 2, y + 8, { align: 'center' })
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(7)
    doc.setTextColor(...MUTED)
    doc.text(item.label.toUpperCase(), x + (colW - 3) / 2, y + 13, { align: 'center' })
  })
  doc.setTextColor(...TEXT)
  return y + 18
}

// ════════════════════════════════════════════════
// ── Export: Report PDF ──────────────────────────
// ════════════════════════════════════════════════
export function downloadReportPDF(opts: {
  title:      string
  orgName?:   string
  period?:    string
  kpis?:      {label:string; value:string|number}[]
  tables?:    { heading: string; columns: string[]; rows: (string|number)[][] }[]
}) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })

  addHeader(doc, opts.title, opts.orgName)

  let y = 36

  // Period / meta
  if (opts.period) {
    doc.setFontSize(9)
    doc.setTextColor(...MUTED)
    doc.text(`Period: ${opts.period}`, 14, y)
    y += 8
  }

  // KPI tiles
  if (opts.kpis?.length) {
    y = sectionTitle(doc, 'Summary', y)
    y = kpiRow(doc, opts.kpis, y)
    y += 6
  }

  // Tables
  for (const t of (opts.tables || [])) {
    if (y > 250) { doc.addPage(); y = 20 }
    y = sectionTitle(doc, t.heading, y)
    autoTable(doc, {
      startY: y,
      head: [t.columns],
      body: t.rows,
      theme: 'striped',
      headStyles: { fillColor: GREEN, textColor: 255, fontSize: 8, fontStyle: 'bold' },
      bodyStyles: { fontSize: 8, textColor: TEXT },
      alternateRowStyles: { fillColor: LIGHT },
      margin: { left: 14, right: 14 },
    })
    y = (doc as any).lastAutoTable.finalY + 10
  }

  addFooter(doc, doc.getNumberOfPages())
  doc.save(`${opts.title.replace(/\s+/g,'-').toLowerCase()}-${new Date().toISOString().slice(0,10)}.pdf`)
}

// ════════════════════════════════════════════════
// ── Export: Invoice PDF ─────────────────────────
// ════════════════════════════════════════════════
export function downloadInvoicePDF(inv: {
  invoiceNumber: string
  amountKes:     number
  plan:          string
  status:        string
  dueDate:       string
  paidAt?:       string
  mpesaCode?:    string
  org?:          { name:string; kraPin?:string; vatNumber?:string; address?:string }
  lineItems?:    { description:string; amount:number }[]
}) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })

  addHeader(doc, 'TAX INVOICE', inv.invoiceNumber)

  let y = 36

  // Issuer details (left)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(9)
  doc.text('Issued by:', 14, y)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.text('Gigs4You Technologies Ltd', 14, y + 5)
  doc.setTextColor(...MUTED)
  doc.text('P.O. Box 12345-00100, Nairobi, Kenya', 14, y + 10)
  doc.text('KRA PIN: P051234567X  |  VAT No: 0123456V', 14, y + 15)
  doc.text('billing@gigs4you.co.ke', 14, y + 20)
  doc.setTextColor(...TEXT)

  // Bill-to (right)
  if (inv.org) {
    doc.setFont('helvetica', 'bold')
    doc.text('Billed to:', 120, y)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...TEXT)
    doc.text(inv.org.name, 120, y + 5)
    if (inv.org.address)    doc.text(inv.org.address, 120, y + 10)
    if (inv.org.kraPin)     doc.text(`KRA PIN: ${inv.org.kraPin}`, 120, y + 15)
    if (inv.org.vatNumber)  doc.text(`VAT No: ${inv.org.vatNumber}`, 120, y + 20)
  }

  y += 30

  // Invoice meta box
  doc.setFillColor(...LIGHT)
  doc.rect(14, y, 182, 22, 'F')
  const dueLabel = inv.status === 'paid'
    ? `Paid on: ${new Date(inv.paidAt!).toLocaleDateString('en-KE', {day:'numeric',month:'long',year:'numeric'})}`
    : `Due date: ${new Date(inv.dueDate).toLocaleDateString('en-KE', {day:'numeric',month:'long',year:'numeric'})}`
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(9)
  doc.text(`Invoice No: ${inv.invoiceNumber}`, 18, y + 7)
  doc.text(`Status: ${inv.status.toUpperCase()}`, 18, y + 14)
  doc.setFont('helvetica', 'normal')
  doc.text(dueLabel, 105, y + 7)
  if (inv.mpesaCode) doc.text(`M-Pesa ref: ${inv.mpesaCode}`, 105, y + 14)
  y += 28

  // Line items table
  y = sectionTitle(doc, 'Services', y)
  autoTable(doc, {
    startY: y,
    head: [['Description', 'Amount (KES)']],
    body: (inv.lineItems?.length
      ? inv.lineItems.map(l => [l.description, `KES ${Number(l.amount).toLocaleString()}`])
      : [[`Gigs4You ${inv.plan} plan — monthly subscription`, `KES ${Number(inv.amountKes).toLocaleString()}`]]
    ),
    theme: 'striped',
    headStyles: { fillColor: GREEN, textColor: 255, fontSize: 9 },
    bodyStyles: { fontSize: 9 },
    columnStyles: { 1: { halign: 'right', fontStyle: 'bold' } },
    margin: { left: 14, right: 14 },
  })
  y = (doc as any).lastAutoTable.finalY + 6

  // Totals — amountKes is the VAT-inclusive grand total (base + 16%)
  // Back-calculate base: base = total / 1.16
  const grandTotal = Math.round(Number(inv.amountKes) * 100) / 100
  const baseAmt    = Math.round((grandTotal / 1.16) * 100) / 100
  const vatAmt     = Math.round((grandTotal - baseAmt) * 100) / 100
  const totals: [string, string][] = [
    ['Subtotal (excl. VAT 16%)', `KES ${baseAmt.toLocaleString()}`],
    ['VAT 16%',                  `KES ${vatAmt.toLocaleString()}`],
    ['TOTAL (VAT inclusive)',     `KES ${grandTotal.toLocaleString()}`],
  ]
  autoTable(doc, {
    startY: y,
    body: totals,
    theme: 'plain',
    bodyStyles: { fontSize: 9 },
    columnStyles: {
      0: { halign: 'right', textColor: MUTED },
      1: { halign: 'right', fontStyle: 'bold', textColor: TEXT },
    },
    margin: { left: 100, right: 14 },
  })
  y = (doc as any).lastAutoTable.finalY + 8

  // Payment instructions
  if (inv.status !== 'paid') {
    doc.setFillColor(...[232, 245, 238] as [number,number,number])
    doc.roundedRect(14, y, 182, 24, 3, 3, 'F')
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(9)
    doc.setTextColor(...GREEN)
    doc.text('Payment Instructions', 18, y + 7)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8)
    doc.setTextColor(...TEXT)
    doc.text('M-Pesa: Paybill 522533  |  Account: ' + inv.invoiceNumber, 18, y + 13)
    doc.text('Bank: Equity Bank  |  A/C: 0123456789  |  Branch: Westlands', 18, y + 19)
  }

  addFooter(doc, doc.getNumberOfPages())
  doc.save(`invoice-${inv.invoiceNumber}.pdf`)
}
